### ISSUE TITLE
Sort by $core not working?

### ISSUE THREAD

**Issue by oaustegard** [SpareCores/sc-www#133]
When attempting to sort the table by $core, sometimes the site just spins ad nauseum, sometimes it shows nothing, other times it randomly sorts by something OTHER than the score per price

E.g. https://sparecores.com/server_prices?gpu_min=1&gpu_memory_min=28&order_by=score_per_price&order_dir=desc

![image](https://github.com/user-attachments/assets/eb6e6bd0-b3b3-4738-b6b8-81ea283a1d90)
![image](https://github.com/user-attachments/assets/c7bab9a8-4ee8-4043-883e-00be766f339e)

Chrome 129.0.6668.100 (Official Build) (64-bit) (cohort: M129 Rollout)
OS | Windows 11 Version 23H2 (Build 22631.4169)
JavaScript | V8 12.9.202.27
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

**Comment by oaustegard** [comment]
Looks like https://keeper.sparecores.net/server_prices?gpu_min=1&gpu_memory_min=28&order_by=score_per_price&order_dir=desc&add_total_count_header=true&limit=25 ends up with a 500 server error

**Comment by daroczig** [comment]
Thanks for the report! The fix is rolling out in 30 minutes.
