### ISSUE TITLE
Sort by performance per dollar

### ISSUE THREAD

**Issue by NoahBPeterson** [SpareCores/sc-www#99]
Hello! I love your site, and I would love to be able to sort by performance per dollar, or at least filter by a minimum performance per dollar.

**Comment by daroczig** [comment]
Thanks for the feedback and feature request, @NoahBPeterson 🙇‍♂️

We have been procrastinating on this for a while due to the performance issue of live joining the min price to all servers in the search API, but thanks to the nudge, we will try to make this happen in a week :)

I'll report back here.

**Comment by daroczig** [comment]
Hi @NoahBPeterson, sorry for the delay with getting back. We faced a few serious performance issues that needed to be handled first regarding merging price and SCore early, but that is now done in the `keeper` repo, and rolling out on the homepage as well.

You can find a new optional column called `$Core` that you can use to sort the records:

![image](https://github.com/user-attachments/assets/4e4eb945-d27c-4575-b53f-ba50b20bad9e)

A new filter for min `$Core` in the sidebar is also rolling out shortly.

Please report back when you have a chance 😊

**Comment by NoahBPeterson** [comment]
Hey @daroczig, thanks for getting back to me!

I see it and it's exactly the information I needed, but sorting is somewhat broken: when sorting by descending, it takes 10-15 seconds to load and then doesn't change the ordering.

**Comment by daroczig** [comment]
Oh, no! It should be much faster thanks to the performance optimization, and should work. Example URL https://sparecores.com/servers?vcpus_min=32&vcpus_max=63&order_by=score_per_price&order_dir=desc (note that you need to select the extra `$Core` column to actually see that it's sorted by that)

Can you pls share the URL where you see this functionality broker? Or share a screenshot/screen recording?

**Comment by NoahBPeterson** [comment]
I cannot reproduce, it works now.

Thank you so much for working on this!

**Comment by daroczig** [comment]
Awesome! Please let me know if you see anything odd. Thanks!

**Comment by oaustegard** [comment]
See #133
